import React, { useRef, useEffect, useState, useCallback } from "react";
import { Terminal as TerminalIcon, Trash2, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

interface TerminalLine {
  id: string;
  type: "input" | "output" | "error" | "info";
  content: string;
}

const COMMANDS: Record<string, (args: string[]) => string[]> = {
  help: () => [
    "Available commands:",
    "  ls          — list project files",
    "  cat <file>  — show file content",
    "  clear       — clear terminal",
    "  version     — show SiteGenie version",
    "  whoami      — show current user info",
    "  pwd         — print working directory",
    "  echo <text> — print text",
    "  git status  — show simulated git status",
    "  git log     — show simulated git log",
    "  npm install — simulate package install",
    "  npm run build — simulate build",
  ],
  version: () => ["SiteGenie v2.0.0 (AI-Powered IDE)"],
  pwd: () => ["/workspace/project"],
  whoami: () => ["sitegenie-user"],
  "git status": () => [
    "On branch main",
    "nothing to commit, working tree clean",
  ],
  "git log": () => [
    "commit a1b2c3d (HEAD -> main)",
    "Author: SiteGenie AI",
    "Date: " + new Date().toDateString(),
    "",
    "    Generated by SiteGenie AI",
  ],
  "npm install": () => [
    "npm warn deprecated: checking packages...",
    "added 0 packages in 0.1s",
    "found 0 vulnerabilities",
  ],
  "npm run build": () => [
    "> sitegenie-project@1.0.0 build",
    "> vite build",
    "",
    "✓ built in 0.8s",
    "dist/index.html  1.23 kB",
    "dist/assets/index-abc123.js  142.31 kB",
    "✓ Build complete",
  ],
};

interface TerminalPanelProps {
  files?: Record<string, string>;
  projectName?: string;
}

export function TerminalPanel({ files = {}, projectName = "project" }: TerminalPanelProps) {
  const [lines, setLines] = useState<TerminalLine[]>([
    { id: "1", type: "info", content: "SiteGenie Terminal v2.0 — Type 'help' for available commands" },
    { id: "2", type: "info", content: `Project: ${projectName}` },
  ]);
  const [input, setInput] = useState("");
  const [history, setHistory] = useState<string[]>([]);
  const [historyIndex, setHistoryIndex] = useState(-1);
  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [lines]);

  const addLine = (type: TerminalLine["type"], content: string) => {
    const id = `${Date.now()}-${Math.random()}`;
    setLines((prev) => [...prev, { id, type, content }]);
  };

  const executeCommand = useCallback((cmd: string) => {
    const trimmed = cmd.trim();
    if (!trimmed) return;

    addLine("input", `$ ${trimmed}`);
    setHistory((prev) => [trimmed, ...prev.slice(0, 49)]);
    setHistoryIndex(-1);

    if (trimmed === "clear") {
      setLines([{ id: Date.now().toString(), type: "info", content: "Terminal cleared" }]);
      return;
    }

    // ls command — list files
    if (trimmed === "ls" || trimmed === "ls -la") {
      const fileList = Object.keys(files);
      if (fileList.length === 0) {
        addLine("output", "(empty project)");
      } else {
        for (const f of fileList) {
          addLine("output", `  ${f}`);
        }
      }
      return;
    }

    // cat command
    if (trimmed.startsWith("cat ")) {
      const path = trimmed.slice(4).trim();
      const normalizedPath = path.startsWith("/") ? path : `/${path}`;
      const content = files[normalizedPath] || files[path];
      if (content) {
        const lines = content.split("\n").slice(0, 30);
        for (const l of lines) addLine("output", l);
        if (content.split("\n").length > 30) {
          addLine("output", `... (${content.split("\n").length - 30} more lines)`);
        }
      } else {
        addLine("error", `cat: ${path}: No such file`);
      }
      return;
    }

    // echo command
    if (trimmed.startsWith("echo ")) {
      addLine("output", trimmed.slice(5));
      return;
    }

    // Check known commands (exact match)
    const knownCmd = COMMANDS[trimmed];
    if (knownCmd) {
      const output = knownCmd([]);
      for (const line of output) addLine("output", line);
      return;
    }

    // Unknown command
    addLine("error", `${trimmed}: command not found. Type 'help' for available commands.`);
  }, [files]);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      executeCommand(input);
      setInput("");
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      const newIndex = Math.min(historyIndex + 1, history.length - 1);
      setHistoryIndex(newIndex);
      setInput(history[newIndex] ?? "");
    } else if (e.key === "ArrowDown") {
      e.preventDefault();
      const newIndex = Math.max(historyIndex - 1, -1);
      setHistoryIndex(newIndex);
      setInput(newIndex === -1 ? "" : (history[newIndex] ?? ""));
    } else if (e.key === "l" && e.ctrlKey) {
      e.preventDefault();
      setLines([{ id: Date.now().toString(), type: "info", content: "Terminal cleared" }]);
    }
  };

  return (
    <div
      className="flex flex-col h-full bg-editor-bg font-mono"
      onClick={() => inputRef.current?.focus()}
    >
      {/* Header */}
      <div className="flex items-center gap-2 px-3 py-1.5 border-b border-editor-border bg-editor-panel shrink-0">
        <TerminalIcon className="w-3.5 h-3.5 text-muted-foreground" />
        <span className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Terminal</span>
        <div className="ml-auto">
          <Button
            variant="ghost"
            size="icon"
            className="h-5 w-5 text-muted-foreground hover:text-foreground"
            onClick={(e) => {
              e.stopPropagation();
              setLines([{ id: Date.now().toString(), type: "info", content: "Terminal cleared" }]);
            }}
          >
            <Trash2 className="w-3 h-3" />
          </Button>
        </div>
      </div>

      {/* Output area */}
      <div className="flex-1 overflow-y-auto p-3 space-y-0.5 min-h-0 text-[11px] leading-5">
        {lines.map((line) => (
          <div
            key={line.id}
            className={cn(
              "whitespace-pre-wrap break-words",
              line.type === "input" ? "text-primary" :
              line.type === "error" ? "text-destructive" :
              line.type === "info" ? "text-chart-2" :
              "text-foreground/80"
            )}
          >
            {line.content}
          </div>
        ))}
        <div ref={bottomRef} />
      </div>

      {/* Input */}
      <div className="flex items-center gap-1.5 px-3 py-2 border-t border-editor-border shrink-0">
        <ChevronRight className="w-3 h-3 text-primary shrink-0" />
        <input
          ref={inputRef}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          className="flex-1 bg-transparent text-[11px] text-foreground outline-none font-mono min-w-0"
          placeholder="Type a command..."
          autoComplete="off"
          spellCheck={false}
        />
      </div>
    </div>
  );
}
