import { corsHeaders } from "../_shared/cors.ts";

interface GitHubRequest {
  token: string;
  username: string;
  repoName: string;
  files: Record<string, string>; // path → content
  isPrivate?: boolean;
}

async function githubFetch(url: string, token: string, options: RequestInit = {}) {
  return fetch(url, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });
}

// Encode string to base64 (Deno compatible)
function toBase64(str: string): string {
  const encoder = new TextEncoder();
  const bytes = encoder.encode(str);
  let binary = "";
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary);
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { token, username, repoName, files, isPrivate = false }: GitHubRequest = await req.json();

    if (!token?.trim()) {
      return new Response(JSON.stringify({ error: "GitHub token is required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (!username?.trim() || !repoName?.trim()) {
      return new Response(JSON.stringify({ error: "Username and repository name are required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const slug = repoName.toLowerCase().replace(/[^a-z0-9-_.]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");

    // Step 1 — Check if repo already exists
    const checkRes = await githubFetch(
      `https://api.github.com/repos/${username}/${slug}`,
      token,
      { method: "GET" }
    );

    let repoUrl: string;

    if (checkRes.status === 404) {
      // Step 2a — Create new repository
      const createRes = await githubFetch("https://api.github.com/user/repos", token, {
        method: "POST",
        body: JSON.stringify({
          name: slug,
          description: `Generated by SiteGenie AI`,
          private: isPrivate,
          auto_init: false,
        }),
      });
      const createData = await createRes.json();
      if (!createRes.ok) {
        const msg = createData?.message || "Failed to create repository";
        return new Response(JSON.stringify({ error: msg }), {
          status: createRes.status, headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      repoUrl = createData.html_url as string;
    } else if (checkRes.ok) {
      const existing = await checkRes.json();
      repoUrl = existing.html_url as string;
    } else {
      const errData = await checkRes.json();
      return new Response(JSON.stringify({ error: errData?.message || "GitHub API error" }), {
        status: checkRes.status, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Step 3 — Push all files (GitHub Contents API, one at a time)
    const fileEntries = Object.entries(files);
    const errors: string[] = [];
    let pushed = 0;

    for (const [path, content] of fileEntries) {
      const filePath = path.startsWith("/") ? path.slice(1) : path;
      const b64 = toBase64(content);

      // Check if file exists to get its sha (needed for update)
      let sha: string | undefined;
      const existingRes = await githubFetch(
        `https://api.github.com/repos/${username}/${slug}/contents/${filePath}`,
        token,
        { method: "GET" }
      );
      if (existingRes.ok) {
        const existingData = await existingRes.json();
        sha = existingData.sha;
      }

      const putRes = await githubFetch(
        `https://api.github.com/repos/${username}/${slug}/contents/${filePath}`,
        token,
        {
          method: "PUT",
          body: JSON.stringify({
            message: sha ? `Update ${filePath}` : `Add ${filePath}`,
            content: b64,
            ...(sha ? { sha } : {}),
          }),
        }
      );

      if (putRes.ok) {
        pushed++;
      } else {
        const errData = await putRes.json();
        errors.push(`${filePath}: ${errData?.message ?? "unknown error"}`);
      }
    }

    if (pushed === 0 && errors.length > 0) {
      return new Response(
        JSON.stringify({ error: `All file uploads failed. First error: ${errors[0]}` }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(
      JSON.stringify({
        success: true,
        url: repoUrl,
        pushed,
        total: fileEntries.length,
        errors: errors.length > 0 ? errors : undefined,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (err) {
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Internal server error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
